// category
export let GET_CATEGORY_PENDING = "GET_CATEGORY_PENDING";
export let GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export let GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";

export let POST_CATEGORY_PENDING = "POST_CATEGORY_PENDING";
export let POST_CATEGORY_SUCCESS = "POST_CATEGORY_SUCCESS";
export let POST_CATEGORY_ERROR = "POST_CATEGORY_ERROR";

export let DELETE_CATEGORY_PENDING = "DELETE_CATEGORY_PENDING";
export let DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export let DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";

export let UPDATE_CATEGORY_PENDING = "UPDATE_CATEGORY_PENDING";
export let UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export let UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";

// prodct
export let GET_PRODUCT_PENDING = "GET_PRODUCT_PENDING";
export let GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export let GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export let POST_PRODUCT_PENDING = "POST_PRODUCT_PENDING";
export let POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export let POST_PRODUCT_ERROR = "POST_PRODUCT_ERROR";

export let DELETE_PRODUCT_PENDING = "DELETE_PRODUCT_PENDING";
export let DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export let DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export let UPDATE_PRODUCT_PENDING = "UPDATE_PRODUCT_PENDING";
export let UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export let UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";


// cart
export let GET_CART_PENDING = "GET_CART_PENDING";
export let GET_CART_SUCCESS = "GET_CART_SUCCESS";
export let GET_CART_ERROR = "GET_CART_ERROR";

export let POST_CART_PENDING = "POST_CART_PENDING";
export let POST_CART_SUCCESS = "POST_CART_SUCCESS";
export let POST_CART_ERROR = "POST_CART_ERROR";

export let DELETE_CART_PENDING = "DELETE_CART_PENDING";
export let DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export let DELETE_CART_ERROR = "DELETE_CART_ERROR";

export let UPDATE_CART_PENDING = "UPDATE_CART_PENDING";
export let UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export let UPDATE_CART_ERROR = "UPDATE_CART_ERROR";

// wishlist
export let GET_WISHLIST_PENDING = "GET_WISHLIST_PENDING";
export let GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export let GET_WISHLIST_ERROR = "GET_WISHLIST_ERROR";

export let POST_WISHLIST_PENDING = "POST_WISHLIST_PENDING";
export let POST_WISHLIST_SUCCESS = "POST_WISHLIST_SUCCESS";
export let POST_WISHLIST_ERROR = "POST_WISHLIST_ERROR";

export let DELETE_WISHLIST_PENDING = "DELETE_WISHLIST_PENDING";
export let DELETE_WISHLIST_SUCCESS = "DELETE_WISHLIST_SUCCESS";
export let DELETE_WISHLIST_ERROR = "DELETE_WISHLIST_ERROR";